import {apiParamValueSettings} from './settings'

const constants = {
    LOAD_MUSICS : "LOAD_MUSICS",
    DATE_CHANGE : "DATE_CHANGE",
    PAGE_MOVE : "PAGE_MOVE",
    SEARCH_KEYWORD_CHANGE : "SEARCH_KEYWORD_CHANGE",
    SEARCH_TYPE_CHANGE : "SEARCH_TYPE_CHANGE",
    SEARCH_BUTTON_CLICK : "SEARCH_BUTTON_CLICK",
    NEXT_BUTTON_CLICK : "NEXT_BUTTON_CLICK",
    PREVIOUS_BUTTON_CLICK : "PREVIOUS_BUTTON_CLICK",
    CHANGE_MUSIC_PLAY_RECORDS : "CHANGE_MUSIC_PLAY_RECORDS",
    CHANGE_PAGINATION_STATE : "CHANGE_PAGINATION_STATE",
    CHANGE_TRANSACTION_INFO : "CHANGE_TRANSACTION_INFO",
    CHANGE_MODAL_SHOW : "CHANGE_MODAL_SHOW",

    SEARCH_BY_USER : apiParamValueSettings.SEARCH_BY_USER,
    SEARCH_BY_MUSIC : apiParamValueSettings.SEARCH_BY_MUSIC,
    SEARCH_BY_USER_WITH_DATE : apiParamValueSettings.SEARCH_BY_USER_WITH_DATE,
    SEARCH_BY_MUSIC_WITH_DATE : apiParamValueSettings.SEARCH_BY_MUSIC_WITH_DATE
}

export default constants
